### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by hyperreal-info** [grompe/magnet2#5]
Hi,
I want to parse a RSS feed and make bot reporting new items to the conference.
What is the best way to integrate that concept with magnet2 in your opinion?

thanks for magnet2! :-)

**Comment by grompe** [comment]
Check how threaded forum access and reporting is done in
https://github.com/grompe/magnet2/blob/master/plugin_room_drawception.py
it should be very similar to what you want.

**Comment by hyperreal-info** [comment]
Thanks :+1:
